import React from 'react'
import Helmet from 'react-helmet'
import { config } from 'config'
import { Link } from 'react-router'
import { prefixLink } from 'gatsby-helpers'

export default class Dions extends React.Component{
    render(){
        return (
        <article>
          <Helmet
            title={config.siteTitle + 'Campus Compass'}
            meta={[
              {"name": "description", "content": "Campus Compass was a university project for #tampere3"},
              {"name": "keywords", "content": "redbeak, campus compass, tampere3"},
            ]}
          />
          <section className="work">
            <div className="work__title">
              <h1>Campus Compass</h1><span className="work__meta--date">February - May 2016</span>
            </div>
            <div className="work__intro">
              <div className="work__desc">
                <h6>Description</h6>
                <p>My first venture into Demola Tampere, an Android application for students that solves navigation between and on campuses. The partner in this venture is #tampere3, an initiative that is working to unify the three main universities of Tampere. In short, our task was to come up with a concept that would promote sustainable travel in addition to the navigation issue.</p>
              </div>
              <div className="work__meta">
                <div className="work__meta--item">
                  <h6>Client / Partner</h6><span>#tampere3</span>
                </div>
                <div className="work__meta--item">
                  <h6>Roles</h6><span>Concept Design, Wireframing, Prototyping, App UI & UX Design, Branding</span>
                </div>
              </div>
            </div>
            <div className="work__full"><img src="banner.jpg" alt="Campus Compass phone mockups banner" />
              <div className="work__tags"><span>Photoshop</span> <span>Illustrator</span> <span>InvisionApp</span></div>
            </div>
            <div className="work__full">
              <h6>Concept </h6>
              <p>Following a lengthy brainstorming period, we decided that the application should be expanded to be a student companion provided by the university. It would solve a number of immediate problems that students face in every day life. These functions include, finding classrooms, class schedule management, bus schedules, student event feed, map of points of interest, emission tracker. Admittedly, these are too numerous and in a real world situation would dilute the application's point. That being said, keeping this work conceptual we allowed ourselves no limits. For the actual mock-up and eventual implementation, we took the best parts, navigation, class scheduling and statistics. </p>
            </div>
            <hr />
            <div className="work__full"><img src="wireframes.jpg" alt="App Initial Wireframes" /></div>
            <div className="work__full">
              <h6>Results</h6>
              <p>As this project was primarily a way to test waters and see if there is any interest on part of the board of #tampere as well as students, we measured the feedback generated by the presentation and pitches of the idea. Technologically speaking, implementing indoor navigation is a fool's errand at this point in time. However, we did make use of the bus schedule and routes provided by an official API of the City of Tampere. Response wise, we got a lot of feedback to the tune of positivity. What students liked the most in our implementation was the possibility to view school schedules and have automatic reminders based on these. In addition to that, optimal bus routes are calculated and presented to the user in the form of a reminder.</p>
            </div>
            <hr />
            <div className="work__full"><img src="shot1.jpg" alt="Mock-up collage" /></div>
            <div className="work__half">
              <div className="work--item"><img src="shot2.jpg" alt="Login and statistics" /></div>
              <div className="work--item"><img src="shot3.jpg" alt="Dashboard" /></div>
            </div>
            <div className="work__full"><img src="shot4.jpg" alt="Second Mock-up collage" /></div>
          </section>
          <div className="work__nav">
            <Link 
              className="work__nav--prev" 
              to={prefixLink("/hiilinielu-design/")}>
              <h6>Previous Case</h6>
              <span>Hiilinielu Design Studio</span>
            </Link>
            <Link 
              className="work__nav--next" 
              to={prefixLink("/dions/")}>
              <h6>Next Case</h6>
              <span>DIONs Infographic</span>
            </Link>
          </div>
        </article>
     )
  }
}